name:                git-list
version:             0.1.0.0
github:              "stefanvonderkrone/git-list"
license:             BSD3
author:              "Stefan von der Krone"
maintainer:          "stefanvonderkrone@gmx.de"
copyright:           "2018 Stefan von der Krone"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/git-list#readme>

dependencies:
- base >= 4.7 && < 5
- turtle
- foldl
- text

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings

executables:
  git-list:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-list

tests:
  git-list-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-list
